### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kpsrinivas** [bigcommerce/gruf-rspec#8]
Getting this error while running tests:
 GRPC::Internal:
       13:Gruf::Controllers::Request::Type#client_streamer? delegated to @rpc_desc.client_streamer?, but @rpc_desc is nil

**Comment by splittingred** [comment]
Hi @kpsrinivas - apologies for the delay - this seems to indicate you haven't bound a gRPC service to the controller?

You'll need to post more information for us to debug further. Thanks!

**Comment by splittingred** [comment]
Closing this - feel free to re-open!
